-- 코드를 입력하세요
# 상반기 아이스크림 총 주문량이 3000보다 높으면서 아이스크림의 주 성분이 과일인 아이스크림 맛을 총 주문량이 큰 순서대로 조회
SELECT A.FLAVOR
FROM FIRST_HALF A JOIN(SELECT FLAVOR, INGREDIENT_TYPE FROM ICECREAM_INFO) B
ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER >= 3000 
AND B.INGREDIENT_TYPE='FRUIT_BASED'

ORDER BY A.TOTAL_ORDER DESC
