-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS A
JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE (A.SEX_UPON_OUTCOME LIKE 'N%' OR A.SEX_UPON_OUTCOME LIKE 'S%') 
    AND B.SEX_UPON_INTAKE LIKE 'INTACT%'
GROUP BY A.ANIMAL_ID
ORDER BY A.ANIMAL_ID
