# -- 코드를 입력하세요
# -- 1번 풀이 : CASE 문 사용
# SELECT ANIMAL_ID, NAME, 
# CASE WHEN (
#     SEX_UPON_INTAKE LIKE "NEUTERED%" OR 
#     SEX_UPON_INTAKE LIKE "SPAYED%") THEN 'O' 
#     ELSE 'X'
#     END AS '중성화'
# FROM ANIMAL_INS
# ORDER BY ANIMAL_ID


-- 2번 풀이 : IF문 사용
SELECT ANIMAL_ID, NAME, 
IF(SEX_UPON_INTAKE LIKE "NEUTERED%" OR SEX_UPON_INTAKE LIKE "SPAYED%", 'O', 'X') AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID